// Argument lengths of associated instructions
unsigned char size_table[16][16] = {
	{0,2,0,0,0,0,1,0,2,0,0,0,0,0,1,0},
	{0,2,0,0,0,0,1,0,1,0,0,0,0,0,1,0},
	{1,2,0,0,0,0,1,0,1,0,0,0,0,0,1,0},
	{1,2,0,0,0,0,1,0,1,0,0,0,0,0,1,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,2,2,2,0,1,0,0,0,2,0,2,2,1,0},
	{0,0,2,0,2,0,1,0,0,0,2,0,2,0,1,0},
	{1,0,0,0,0,0,1,0,1,0,2,0,0,0,1,0},
	{1,0,0,0,0,0,1,0,1,0,2,0,0,0,1,0}
};

// Offsets of data insertion points
unsigned char offset_table[16][16] = {
	{0,4,0,0,0,0,3,0,2,0,0,0,0,0,3,0},
	{0,4,0,0,0,0,3,0,1,0,0,0,0,0,3,0},
	{4,4,0,0,0,0,3,0,3,0,0,0,0,0,3,0},
	{4,4,0,0,0,0,6,0,3,0,0,0,0,0,3,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
	{0,0,4,1,4,0,3,0,0,0,3,0,3,1,3,0},
	{0,0,4,0,4,0,1,0,0,0,3,0,3,0,3,0},
	{2,0,0,0,0,0,1,0,4,0,2,0,0,0,1,0},
	{4,0,0,0,0,0,1,0,7,0,4,0,0,0,1,0}
};

// Non-prefixed gbz80 instructions
char* opcode_table[16][16] = {
	{"nop",   "ld",    "ld",    "inc",   "inc",   "dec",   "ld",    "rlca",
	 "ld",    "add",   "ld",    "dec",   "inc",   "dec",   "ld",    "rrca"},
	{"stop",  "ld",    "ld",    "inc",   "inc",   "dec",   "ld",    "rla",
	 "jr",    "add",   "ld",    "dec",   "inc",   "dec",   "ld",    "rra"},
	{"jr",    "ld",    "ld",    "inc",   "inc",   "dec",   "ld",    "daa",
	 "jr",    "add",   "ld",    "dec",   "inc",   "dec",   "ld",    "cpl"},
	{"jr",    "ld",    "ld",    "inc",   "inc",   "dec",   "ld",    "scf",
	 "jr",    "add",   "ld",    "dec",   "inc",   "dec",   "ld",    "ccf"},
	{"ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",
	 "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld"},
	{"ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",
	 "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld"},
	{"ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",
	 "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld"},
	{"ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "halt",  "ld",
	 "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld",    "ld"},
	{"add",   "add",   "add",   "add",   "add",   "add",   "add",   "add",
	 "adc",   "adc",   "adc",   "adc",   "adc",   "adc",   "adc",   "adc"},
	{"sub",   "sub",   "sub",   "sub",   "sub",   "sub",   "sub",   "sub",
	 "sbc",   "sbc",   "sbc",   "sbc",   "sbc",   "sbc",   "sbc",   "sbc"},
	{"and",   "and",   "and",   "and",   "and",   "and",   "and",   "and",
	 "xor",   "xor",   "xor",   "xor",   "xor",   "xor",   "xor",   "xor"},
	{"or",    "or",    "or",    "or",    "or",    "or",    "or",    "or",
	 "cp",    "cp",    "cp",    "cp",    "cp",    "cp",    "cp",    "cp"},
	{"ret",   "pop",   "jp",    "jp",    "call",  "push",  "add",   "rst",
	 "ret",   "ret",   "jp",    "-",     "call",  "call",  "adc",   "rst"},
	{"ret",   "pop",   "jp",    "-",     "call",  "push",  "sub",   "rst",
	 "ret",   "reti",  "jp",    "-",     "call",  "-",     "sbc",   "rst"},
	{"ldh",   "pop",   "ld",    "-",     "-",     "push",  "and",   "rst",
	 "add",   "jp",    "ld",    "-",     "-",     "-",     "xor",   "rst"},
	{"ldh",   "pop",   "ld",    "di",    "-",     "push",  "or",    "rst",
	 "ld",    "ld",    "ld",    "ei",     "-",     "-",     "cp",    "rst"}
};

// Non-prefixed gbz80 parameters
char* param_table[16][16] = {
	{"",            "bc,$xxyy",  "(bc),a",     "bc",
	 "b",           "b",         "b,$xx",      "",
	 "($xxyy),sp",  "hl,bc",     "a,(bc)",     "bc",
	 "c",           "c",         "c,$xx",      ""},
	{"",           "de,$xxyy",  "(de),a",     "de",
	 "d",           "d",         "d,$xx",      "",
	 "$xx",         "hl,de",     "a,(de)",     "de",
	 "e",           "e",         "e,$xx",      ""},
	{"nz,$xx",      "hl,$xxyy",  "(hli),a",    "hl",
	 "h",           "h",         "h,$xx",      "",
	 "z,$xx",       "hl,hl",     "a,(hli)",    "hl",
	 "l",           "l",         "l,$xx",      ""},
	{"nc,$xx",      "sp,$xxyy",  "(hld),a",    "sp",
	 "(hl)",        "(hl)",      "(hl),$xx",   "",
	 "c,$xx",       "hl,sp",     "a,(hld)",    "sp",
	 "a",           "a",         "a,$xx",      ""},
	{"b,b",         "b,c",       "b,d",        "b,e",
	 "b,h",         "b,l",       "b,(hl)",     "b,a",
	 "c,b",         "c,c",       "c,d",        "c,e",
	 "c,h",         "c,l",       "c,(hl)",     "c,a"},
	{"d,b",         "d,c",       "d,d",        "d,e",
	 "d,h",         "d,l",       "d,(hl)",     "d,a",
	 "e,b",         "e,c",       "e,d",        "e,e",
	 "e,h",         "e,l",       "e,(hl)",     "e,a"},
	{"h,b",         "h,c",       "h,d",        "h,e",
	 "h,h",         "h,l",       "h,(hl)",     "h,a",
	 "l,b",         "l,c",       "l,d",        "l,e",
	 "l,h",         "l,l",       "l,(hl)",     "l,a"},
	{"(hl),b",      "(hl),c",    "(hl),d",     "(hl),e",
	 "(hl),h",      "(hl),l",    "",           "(hl),a",
	 "a,b",         "a,c",       "a,d",        "a,e",
	 "a,h",         "a,l",       "a,(hl)",     "a,a"},
	{"a,b",         "a,c",       "a,d",        "a,e",
	 "a,h",         "a,l",       "a,(hl)",     "a,a",
	 "a,b",         "a,c",       "a,d",        "a,e",
	 "a,h",         "a,l",       "a,(hl)",     "a,a"},
	{"b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a",
	 "a,b",         "a,c",       "a,d",        "a,e",
	 "a,h",         "a,l",       "a,(hl)",     "a,a"},
	{"b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a",
	 "b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a"},
	{"b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a",
	 "b",           "c",         "d",          "e",
	 "h",           "l",         "(hl)",       "a"},
	{"nz",          "bc",        "nz,$xxyy",   "$xxyy",
	 "nz,$xxyy",    "bc",        "a,$xx",      "00h",
	 "z",           "",          "z,$xxyy",    "cb",
	 "z,$xxyy",     "$xxyy",     "a,$xx",      "08h"},
	{"nc",          "de",        "nc,$xxyy",   "",
	 "nc,$xxyy",    "de",        "$xx",        "10h",
	 "c",           "",          "c,$xxyy",    "",
	 "c,$xxyy",     "",          "a,$xx",      "18h"},
	{"($xx),a",     "hl",        "(c),a",      "",
	 "",            "hl",        "$xx",        "20h",
	 "sp,$xx",      "hl",      "($xxyy),a",  "",
	 "",            "",          "$xx",        "28h"},
	{"a,($xx)",     "af",        "a,(c)",      "",
	 "",            "af",        "$xx",        "30h",
	 "hl,sp+$xx",   "sp,hl",     "a,($xxyy)",  "",
	 "",            "",          "$xx",        "38h"}
};

// Prefixed gbz80 instructions
char *cb_opcode_table[16][16] = {
	{"rlc",   "rlc",   "rlc",   "rlc",   "rlc",   "rlc",   "rlc",   "rlc",
	 "rrc",   "rrc",   "rrc",   "rrc",   "rrc",   "rrc",   "rrc",   "rrc"},
	{"rl",    "rl",    "rl",    "rl",    "rl",    "rl",    "rl",    "rl",
	 "rr",    "rr",    "rr",    "rr",    "rr",    "rr",    "rr",    "rr"},
	{"sla",   "sla",   "sla",   "sla",   "sla",   "sla",   "sla",   "sla",
	 "sra",   "sra",   "sra",   "sra",   "sra",   "sra",   "sra",   "sra"},
	{"swap",  "swap",  "swap",  "swap",  "swap",  "swap",  "swap",  "swap",
	 "srl",   "srl",   "srl",   "srl",   "srl",   "srl",   "srl",   "srl"},
	{"bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",
	 "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit"},
	{"bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",
	 "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit"},
	{"bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",
	 "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit"},
	{"bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",
	 "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit",   "bit"},
	{"res",   "res",   "res",   "res",   "res",   "res",   "res",   "res",
	 "res",   "res",   "res",   "res",   "res",   "res",   "res",   "res"},
	{"res",   "res",   "res",   "res",   "res",   "res",   "res",   "res",
	 "res",   "res",   "res",   "res",   "res",   "res",   "res",   "res"},
	{"res",   "res",   "res",   "res",   "res",   "res",   "res",   "res",
	 "res",   "res",   "res",   "res",   "res",   "res",   "res",   "res"},
	{"res",   "res",   "res",   "res",   "res",   "res",   "res",   "res",
	 "res",   "res",   "res",   "res",   "res",   "res",   "res",   "res"},
	{"set",   "set",   "set",   "set",   "set",   "set",   "set",   "set",
	 "set",   "set",   "set",   "set",   "set",   "set",   "set",   "set"},
	{"set",   "set",   "set",   "set",   "set",   "set",   "set",   "set",
	 "set",   "set",   "set",   "set",   "set",   "set",   "set",   "set"},
	{"set",   "set",   "set",   "set",   "set",   "set",   "set",   "set",
	 "set",   "set",   "set",   "set",   "set",   "set",   "set",   "set"},
	{"set",   "set",   "set",   "set",   "set",   "set",   "set",   "set",
	 "set",   "set",   "set",   "set",   "set",   "set",   "set",   "set"}
};

// Prefixed gbz80 parameters
char *cb_param_table[16][16] = {
	{"b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a",
	 "b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a"},
	{"b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a",
	 "b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a"},
	{"b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a",
	 "b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a"},
	{"b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a",
	 "b",    "c",    "d",    "e",    "h",    "l",    "(hl)",    "a"},
	{"0,b",  "0,c",  "0,d",  "0,e",  "0,h",  "0,l",  "0,(hl)",  "0,a",
	 "1,b",  "1,c",  "1,d",  "1,e",  "1,h",  "1,l",  "1,(hl)",  "1,a"},
	{"2,b",  "2,c",  "2,d",  "2,e",  "2,h",  "2,l",  "2,(hl)",  "2,a",
	 "3,b",  "3,c",  "3,d",  "3,e",  "3,h",  "3,l",  "3,(hl)",  "3,a"},
	{"4,b",  "4,c",  "4,d",  "4,e",  "4,h",  "4,l",  "4,(hl)",  "4,a",
	 "5,b",  "5,c",  "5,d",  "5,e",  "5,h",  "5,l",  "5,(hl)",  "5,a"},
	{"6,b",  "6,c",  "6,d",  "6,e",  "6,h",  "6,l",  "6,(hl)",  "6,a",
	 "7,b",  "7,c",  "7,d",  "7,e",  "7,h",  "7,l",  "7,(hl)",  "7,a"},
	{"0,b",  "0,c",  "0,d",  "0,e",  "0,h",  "0,l",  "0,(hl)",  "0,a",
	 "1,b",  "1,c",  "1,d",  "1,e",  "1,h",  "1,l",  "1,(hl)",  "1,a"},
	{"2,b",  "2,c",  "2,d",  "2,e",  "2,h",  "2,l",  "2,(hl)",  "2,a",
	 "3,b",  "3,c",  "3,d",  "3,e",  "3,h",  "3,l",  "3,(hl)",  "3,a"},
	{"4,b",  "4,c",  "4,d",  "4,e",  "4,h",  "4,l",  "4,(hl)",  "4,a",
	 "5,b",  "5,c",  "5,d",  "5,e",  "5,h",  "5,l",  "5,(hl)",  "5,a"},
	{"6,b",  "6,c",  "6,d",  "6,e",  "6,h",  "6,l",  "6,(hl)",  "6,a",
	 "7,b",  "7,c",  "7,d",  "7,e",  "7,h",  "7,l",  "7,(hl)",  "7,a"},
	{"0,b",  "0,c",  "0,d",  "0,e",  "0,h",  "0,l",  "0,(hl)",  "0,a",
	 "1,b",  "1,c",  "1,d",  "1,e",  "1,h",  "1,l",  "1,(hl)",  "1,a"},
	{"2,b",  "2,c",  "2,d",  "2,e",  "2,h",  "2,l",  "2,(hl)",  "2,a",
	 "3,b",  "3,c",  "3,d",  "3,e",  "3,h",  "3,l",  "3,(hl)",  "3,a"},
	{"4,b",  "4,c",  "4,d",  "4,e",  "4,h",  "4,l",  "4,(hl)",  "4,a",
	 "5,b",  "5,c",  "5,d",  "5,e",  "5,h",  "5,l",  "5,(hl)",  "5,a"},
	{"6,b",  "6,c",  "6,d",  "6,e",  "6,h",  "6,l",  "6,(hl)",  "6,a",
	 "7,b",  "7,c",  "7,d",  "7,e",  "7,h",  "7,l",  "7,(hl)",  "7,a"}
};

// List of prefixed instructions for quick comparison
char *cb_set[11] = {"bit","res","rl","rlc","rr","rrc","set","sla","sra","srl","swap"};

